version: '2'
services:
  mysql:
    image: 'docker.io/library/mariadb:10.5'
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=happy
      - MYSQL_USER=m0724001
      - MYSQL_PASSWORD=nuuCSIE404
      - MYSQL_DATABASE=mqtt
    volumes:
      - 'mysql_data:/var/lib/mysql'
      # 自動化匯入架構機制 imported by default to the database specified by the MYSQL_DATABASE variable
      - './emqx-auth-mysql-init.sql:/docker-entrypoint-initdb.d/emqx-auth-mysql-init.sql'
      # 預設MQTT使用者帳號密碼清單
      - './mqtt_user_list.sql:/docker-entrypoint-initdb.d/mqtt_user_list.sql'
  
  admiral:
    image: adminer
    ports:
      - 3280:8080

  emqtt:
    image: 'emqx/emqx-edge:v4.1.3'
    restart: always
    depends_on:
      - mysql
    environment:
      # 反向代理
      - VIRTUAL_HOST=emqx.rpi.mlc.app
      - LETSENCRYPT_HOST=emqx.rpi.mlc.app
      - VIRTUAL_PORT=18083
      - LETSENCRYPT_EMAIL=m0724001@gm.nuu.edu.tw
      # 管理預設帳號與密碼
      - EMQX_DASHBOARD__DEFAULT_USER__LOGIN=m0724001
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=nuuCSIE404
      # EMQ設定組態
      - EMQX_WAIT_TIME=5
      - EMQ_NAME="smarthome-edge"
      - EMQ_HOST="emqtt"
      - PLATFORM_ETC_DIR=/opt/emqx/etc
      - PLATFORM_LOG_DIR=/opt/emqx/log
      - EMQX_NODE__NAME=smarthome-edge@emqtt
      - EMQX_LOG__CONSOLE=console
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQ_LISTENER__TCP__EXTERNAL=1883
      - EMQ_LISTENER__SSL__EXTERNAL=8883
      - EMQX_LISTENER__WS__EXTERNAL=8083
      - EMQX_LISTENER__WSS__EXTERNAL=8084
      - EMQX_LISTENER__API__MGMT=8080
      - EMQX_MQTT__MAX_PACKET_SIZE=64KB
      - EMQX_LOADED_PLUGINS="emqx_management,emqx_auth_mysql,emqx_recon,emqx_rule_engine,emqx_retainer,emqx_dashboard"
      # 連線數量設定
      - EMQX_LISTENER__WSS__EXTERNAL__MAX_CONNECTIONS=100
      # EMQ憑證組態
      - EMQX_LISTENER__SSL__EXTERNAL__KEYFILE=/certs/emqx.rpi.mlc.app.key
      - EMQX_LISTENER__SSL__EXTERNAL__CERTFILE=/certs/emqx.rpi.mlc.app.crt
      - EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE=/certs/emqx.rpi.mlc.app.chain.pem
      - EMQX_LISTENER__SSL__EXTERNAL__DHFILE=/certs/emqx.rpi.mlc.app.dhparam.pem
      - EMQX_LISTENER__WSS__EXTERNAL__KEYFILE=/certs/emqx.rpi.mlc.app.key
      - EMQX_LISTENER__WSS__EXTERNAL__CERTFILE=/certs/emqx.rpi.mlc.app.crt
      - EMQX_LISTENER__WSS__EXTERNAL__CACERTFILE=/certs/emqx.rpi.mlc.app.chain.pem
      - EMQX_LISTENER__WSS__EXTERNAL__DHFILE=/certs/emqx.rpi.mlc.app.dhparam.pem
      # EMQ emqx_auth_mysql外掛組態
      - EMQX_AUTH__MYSQL__SERVER=mysql:3306
      - EMQX_AUTH__MYSQL__USERNAME=root
      - EMQX_AUTH__MYSQL__PASSWORD=happy
      - EMQX_AUTH__MYSQL__DATABASE=mqtt
      - EMQX_AUTH__MYSQL__QUERY_TIMEOUT=30s
      - "EMQX_AUTH__MYSQL__AUTH_QUERY=SELECT password, salt FROM mqtt_user WHERE username = '%u'"
      # EMQ emqx_auth_mysql 使用者密碼均為sha256(salt+密碼)後的結果
      - EMQX_AUTH__MYSQL__PASSWORD_HASH=salt,sha256
      # EMQ emqx_bridge_mqtt(橋接至第一個MQTT伺服器 nuu.cloud)
      - EMQX_BRIDGE__MQTT__NUUCLOUD__ADDRESS=120.105.128.223:1883
      - EMQX_BRIDGE__MQTT__NUUCLOUD__CLIENTID=smarthome_rpi
      - EMQX_BRIDGE__MQTT__NUUCLOUD__CLEAN_START=true
      - EMQX_BRIDGE__MQTT__NUUCLOUD__USERNAME=nuu@nuucloud.com
      - EMQX_BRIDGE__MQTT__NUUCLOUD__PASSWORD=5271e715bf341ddbf72d2b69a0c598c539cc9ece919be8210731ca634bbd29ea
      - EMQX_BRIDGE__MQTT__NUUCLOUD__SSL=off
      - EMQX_BRIDGE__MQTT__NUUCLOUD__FORWARDS=#
      - EMQX_BRIDGE__MQTT__NUUCLOUD__MOUNTPOINT=/smarthome/
      # EMQ WEBHOOK組態
      - EMQX_WEB__HOOK__API__URL=http://emqtt:8080
      # EMQ emqx_auth_http(http認證組態)
      - EMQX_AUTH__HTTP__AUTH_REQ=http://emqtt:8991/mqtt/auth
      - EMQX_AUTH__HTTP__AUTH_REQ__METHOD=post
      - EMQX_AUTH__HTTP__AUTH_REQ__PARAMS=clientid=%c,username=%u,password=%P
      - EMQX_AUTH__HTTP__SUPER_REQ__METHOD=post
      - EMQX_AUTH__HTTP__SUPER_REQ__PARAMS=clientid=%c,username=%u
      # 
      - EMQX_AUTH__HTTP__ACL_REQ=http://emqtt:8080/mqtt/acl
      - EMQX_AUTH__HTTP__ACL_REQ__METHOD=get
      - EMQX_AUTH__HTTP__REQUEST__RETRY_TIMES=3
      - EMQX_AUTH__HTTP__ACL_REQ__PARAMS=access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t
      - EMQX_AUTH__HTTP__SUPER_REQ=http://emqtt:8991/mqtt/superuser
    ports:
      - 8883:8883
      - 1883:1883
      - 11883:11883
      - 18083:18083
      #- 8080:8080
      - 8083:8083
      - 8084:8084
    expose:
      - 8080
      - 8991
    volumes:
      # 內建有效憑證
      - /home/ubuntu/docker-rpi-reverse-proxy-companion/certs:/certs:rw
      # 橋接環境設定
      - ./emqx_bridge_mqtt.conf:/opt/emqx/etc/plugins/emqx_bridge_mqtt.conf:rw
      # 永久儲存空間
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log

volumes:
  vol-emqx-data:
    driver: local
  vol-emqx-etc:
    driver: local
  vol-emqx-log:
    driver: local
  mysql_data:
    driver: local
